<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Jobs\Job.IdentifyList.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Jobs\Job.IdentifyList.cs" />
  </ItemGroup>

</Project>
