// <auto-generated />
using System;
using AgroEco.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroEco.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260810212324_cambio3")]
    partial class cambio3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AgroEco.Core.Jobs.Actions.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Actions", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TriggerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TriggerId");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Triggers.Trigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Triggers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Actions.Implementations.actionTest", b =>
                {
                    b.HasBaseType("AgroEco.Core.Jobs.Actions.Action");

                    b.ToTable("ActionTests", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Triggers.Implementations.DateTimeTrigger", b =>
                {
                    b.HasBaseType("AgroEco.Core.Jobs.Triggers.Trigger");

                    b.ToTable("DateTimeTrigger", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Actions.Action", b =>
                {
                    b.HasOne("AgroEco.Core.Jobs.Job", null)
                        .WithMany("Action")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Job", b =>
                {
                    b.HasOne("AgroEco.Core.Jobs.Triggers.Trigger", "Trigger")
                        .WithMany()
                        .HasForeignKey("TriggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Actions.Implementations.actionTest", b =>
                {
                    b.HasOne("AgroEco.Core.Jobs.Actions.Action", null)
                        .WithOne()
                        .HasForeignKey("AgroEco.Core.Jobs.Actions.Implementations.actionTest", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Triggers.Implementations.DateTimeTrigger", b =>
                {
                    b.HasOne("AgroEco.Core.Jobs.Triggers.Trigger", null)
                        .WithOne()
                        .HasForeignKey("AgroEco.Core.Jobs.Triggers.Implementations.DateTimeTrigger", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Job", b =>
                {
                    b.Navigation("Action");
                });
#pragma warning restore 612, 618
        }
    }
}
