// <auto-generated />
using System;
using AgroEco.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroEco.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20261008205519_RemoveUmbralSensor")]
    partial class RemoveUmbralSensor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AgroEco.Core.Alerts.AlertDeliveryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlertEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlertEntityId");

                    b.HasIndex("AlertId");

                    b.HasIndex("ChannelType");

                    b.ToTable("AlertDeliveries", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Alerts.AlertEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Level");

                    b.HasIndex("Status");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Finanzas.RegistroFinanciero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cultivo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("TaskId");

                    b.HasIndex("Tipo");

                    b.ToTable("RegistrosFinancieros", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Inventario.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("Caducidad")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cultivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Finca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Nombre");

                    b.ToTable("Insumos", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Actions.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Actions", (string)null);

                    b.HasDiscriminator<string>("ActionType").HasValue("Action");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TriggerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TriggerId");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Runs.JobRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TriggerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TriggeredBy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("StartedAt");

                    b.ToTable("JobRuns", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Runs.JobRunAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("JobRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId");

                    b.ToTable("JobRunActions", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Triggers.Events.TriggerEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JobRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TriggerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TriggerId");

                    b.ToTable("TriggerEvents", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Triggers.Trigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiredCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastFiredAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxExecutions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Triggers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Actions.Implementations.ExecuteTaskAction", b =>
                {
                    b.HasBaseType("AgroEco.Core.Jobs.Actions.Action");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ExecuteTaskConfig");

                    b.HasDiscriminator().HasValue("executeTask");
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Actions.Implementations.NoOpAction", b =>
                {
                    b.HasBaseType("AgroEco.Core.Jobs.Actions.Action");

                    b.HasDiscriminator().HasValue("noop");
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Actions.Implementations.SendAlertAction", b =>
                {
                    b.HasBaseType("AgroEco.Core.Jobs.Actions.Action");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SendAlertConfig");

                    b.HasDiscriminator().HasValue("sendAlert");
                });

            modelBuilder.Entity("AgroEco.Core.Triggers.Implementations.CronTrigger", b =>
                {
                    b.HasBaseType("AgroEco.Core.Triggers.Trigger");

                    b.ToTable("CronTrigger", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Triggers.Implementations.DateTimeTrigger", b =>
                {
                    b.HasBaseType("AgroEco.Core.Triggers.Trigger");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TargetTime")
                        .HasColumnType("TEXT");

                    b.ToTable("DateTimeTrigger", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Alerts.AlertDeliveryEntity", b =>
                {
                    b.HasOne("AgroEco.Core.Alerts.AlertEntity", null)
                        .WithMany("Deliveries")
                        .HasForeignKey("AlertEntityId");
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Actions.Action", b =>
                {
                    b.HasOne("AgroEco.Core.Jobs.Job", null)
                        .WithMany("Actions")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Job", b =>
                {
                    b.HasOne("AgroEco.Core.Triggers.Trigger", "Trigger")
                        .WithMany()
                        .HasForeignKey("TriggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Runs.JobRunAction", b =>
                {
                    b.HasOne("AgroEco.Core.Jobs.Runs.JobRun", null)
                        .WithMany("Actions")
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroEco.Core.Triggers.Implementations.CronTrigger", b =>
                {
                    b.HasOne("AgroEco.Core.Triggers.Trigger", null)
                        .WithOne()
                        .HasForeignKey("AgroEco.Core.Triggers.Implementations.CronTrigger", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AgroEco.Core.Triggers.Configuration.CronTriggerConfiguration", "Config", b1 =>
                        {
                            b1.Property<int>("CronTriggerId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CronExpression")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("CronExpression");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("EndDate");

                            b1.Property<DateOnly?>("StartDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("StartDate");

                            b1.Property<string>("TimeZone")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("TimeZone");

                            b1.HasKey("CronTriggerId");

                            b1.ToTable("CronTrigger");

                            b1.WithOwner()
                                .HasForeignKey("CronTriggerId");
                        });

                    b.Navigation("Config")
                        .IsRequired();
                });

            modelBuilder.Entity("AgroEco.Core.Triggers.Implementations.DateTimeTrigger", b =>
                {
                    b.HasOne("AgroEco.Core.Triggers.Trigger", null)
                        .WithOne()
                        .HasForeignKey("AgroEco.Core.Triggers.Implementations.DateTimeTrigger", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroEco.Core.Alerts.AlertEntity", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Job", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Runs.JobRun", b =>
                {
                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
