// <auto-generated />
using System;
using AgroEco.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroEco.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20261007013948_AddActionDiscriminatorAndConfig")]
    partial class AddActionDiscriminatorAndConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AgroEco.Core.Alerts.AlertDeliveryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlertEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlertEntityId");

                    b.HasIndex("AlertId");

                    b.HasIndex("ChannelType");

                    b.ToTable("AlertDeliveries", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Alerts.AlertEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Level");

                    b.HasIndex("Status");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Finanzas.RegistroFinanciero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cultivo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("TaskId");

                    b.HasIndex("Tipo");

                    b.ToTable("RegistrosFinancieros", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Inventario.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("Caducidad")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cultivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Finca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Nombre");

                    b.ToTable("Insumos", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Actions.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Actions", (string)null);

                    b.HasDiscriminator<string>("ActionType").HasValue("Action");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TriggerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TriggerId");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Triggers.Trigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Triggers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Actions.Implementations.ExecuteTaskAction", b =>
                {
                    b.HasBaseType("AgroEco.Core.Jobs.Actions.Action");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ExecuteTaskConfig");

                    b.HasDiscriminator().HasValue("executeTask");
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Actions.Implementations.NoOpAction", b =>
                {
                    b.HasBaseType("AgroEco.Core.Jobs.Actions.Action");

                    b.HasDiscriminator().HasValue("noop");
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Actions.Implementations.SendAlertAction", b =>
                {
                    b.HasBaseType("AgroEco.Core.Jobs.Actions.Action");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SendAlertConfig");

                    b.HasDiscriminator().HasValue("sendAlert");
                });

            modelBuilder.Entity("AgroEco.Core.Triggers.Implementations.DateTimeTrigger", b =>
                {
                    b.HasBaseType("AgroEco.Core.Triggers.Trigger");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TargetTime")
                        .HasColumnType("TEXT");

                    b.ToTable("DateTimeTrigger", (string)null);
                });

            modelBuilder.Entity("AgroEco.Core.Alerts.AlertDeliveryEntity", b =>
                {
                    b.HasOne("AgroEco.Core.Alerts.AlertEntity", null)
                        .WithMany("Deliveries")
                        .HasForeignKey("AlertEntityId");
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Actions.Action", b =>
                {
                    b.HasOne("AgroEco.Core.Jobs.Job", null)
                        .WithMany("Actions")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Job", b =>
                {
                    b.HasOne("AgroEco.Core.Triggers.Trigger", "Trigger")
                        .WithMany()
                        .HasForeignKey("TriggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("AgroEco.Core.Triggers.Implementations.DateTimeTrigger", b =>
                {
                    b.HasOne("AgroEco.Core.Triggers.Trigger", null)
                        .WithOne()
                        .HasForeignKey("AgroEco.Core.Triggers.Implementations.DateTimeTrigger", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgroEco.Core.Alerts.AlertEntity", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("AgroEco.Core.Jobs.Job", b =>
                {
                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
